POST https://localhost/cairnsgames/php/auth/changepassword.php?debug=true
Content-Type: application/json
app_id: b0181e17-e5c6-11ee-bb99-1a220d8ac2c9

{
  "userid": null,
  "oldpassword": "pik0bqVaIkv1oaGV39Xd6ZuLvaz7RoH5CG5JOEGfYI492Wv4kCvO6jf1Mf8Dgo9qqDHW0BZtsJ7NOMVuoNOSD5nVPYUCq30ZSGXGXzm4Cwc43HxUZ9BGCGK6Rk2UdLAVUVkByNC7sqksRsFJ78QKh6JLbcEVw7j51fPIMe1MNHlweKqbQSvySo0ECHsEyJCMPTy86v5L",
  "password": "123",
  "password2": "123"
}