POST https://localhost/cairnsgames/php/kloko/api.php/events?lat=26&lng=26
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOm51bGwsInN1YiI6bnVsbCwiYXVkIjpudWxsLCJleHAiOjE4MTEyMjM3MjksIm5iZiI6MTc1MDc0MzcyOSwiaWF0IjoxNzUwNzQzNzI5LCJqdGkiOiJ7NzczRUJBODMtNkU2OC0yMDVCLTVBQzktNkY1MTNBRDg4RjI5fSIsImRhdGEiOnsiaWQiOjE1MTAsInVzZXJuYW1lIjpudWxsLCJmaXJzdG5hbWUiOiJJcGhvbmUiLCJsYXN0bmFtZSI6IkNhaXJucyIsInJvbGUiOm51bGwsInBlcm1pc3Npb25zIjpbeyJuYW1lIjoiQXV0aCIsInBlcm1pc3Npb24iOiJZRVMifSx7Im5hbWUiOiJDYWxlbmRhciIsInBlcm1pc3Npb24iOiJZRVMifSx7Im5hbWUiOiJFdmVudHMiLCJwZXJtaXNzaW9uIjoiWUVTIn0seyJuYW1lIjoiSW1wZXJzb25hdGVVc2VyIiwicGVybWlzc2lvbiI6Ik5PIn0seyJuYW1lIjoiTG95YWx0eSIsInBlcm1pc3Npb24iOiJZRVMifSx7Im5hbWUiOiJNZW1iZXJzaGlwQWRtaW5pc3RyYXRpb24iLCJwZXJtaXNzaW9uIjoiTk8ifSx7Im5hbWUiOiJPcmRlcnMiLCJwZXJtaXNzaW9uIjoiTk8ifSx7Im5hbWUiOiJQYXJ0bmVyIiwicGVybWlzc2lvbiI6IllFUyJ9LHsibmFtZSI6IlN0b3JlIiwicGVybWlzc2lvbiI6Ik5PIn0seyJuYW1lIjoiVGVuYW50IiwicGVybWlzc2lvbiI6Ik5PIn1dfX0.ZDU4OTFmNzllYTA3Njc3NDRmZjI0NTNkMWJiOWUxY2Q0YmFjYmI5MDAzYTNjNGE5ZGRjYWY1NTBkMzc2MWY3MA
app_id: b0181e17-e5c6-11ee-bb99-1a220d8ac2c9
Content-Type: application/json

{

  "lat": -26.0847222,
  "lng": 27.9894444,
"distance": 50
}